language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - cd front
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: server/public
  fqdn: bfban.com
  on:
    branch: master
