language: node_js
node_js:
  - "14.17.6"
cache:
  directories:
    - node_modules
script:
  - cd front
  - npm install
  - npm run serve
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: front/dist
  fqdn: bfban.com
  on:
    branch: master
