# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pages-build-deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    # 该项目请使用指定的node
    # Use the specified node for this project
    strategy:
      matrix:
        node-version: [14.17.6]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./front
    - run: npm run build --if-present
      working-directory: ./front

    - name: Commit changes
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: './front/dist'
        commit-message: 'build front'
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "."
        target: "/var/www/bfban-testing"
